name: CI
on:
  push:
  pull_request:
jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt
      - name: Build
        run: cargo build --all-targets --verbose
      - name: Test
        run: cargo test --all --verbose
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Fmt
        run: cargo fmt --all -- --check
